# Generated by Django 4.1.7 on 2023-10-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
